### ISSUE TITLE
Tag Releases

### ISSUE THREAD

**Issue by MatthewCawley** [SwiftUIX/SwiftUIX#102]
Please can you start tagging releases.

The changes to the RectangleCorner API made breaking changes to my project which took ages to track down. As everything is running from Master, reverting to previous commits was not easy.

Tagging release will avoid issues when breaking changes are made.

Thanks

**Comment by vmanot** [comment]
Hey Matthew, I'm extremely sorry to hear about the trouble you faced. I've been planning to tag release for quite some time right now - was waiting for SwiftUI 2 to come out so that I could review the current API surface and clean it up for a proper "1.0". But given that I'm indeed making quite a few breaking changes in the coming weeks, I'll tag the current `master` as a 0.0.1 or something. 

Thank you for raising this issue :)

**Comment by MatthewCawley** [comment]
Hi Vatsal,

Thank you for replying. Tagging before SwiftUI 2 comes out would be very beneficial especially for user's that do not initially move to SwiftUI 2 and want to stay on the old codebase.

That would be great to start a 0.0.1 and work from there :)

**Comment by vmanot** [comment]
@MatthewCawley oh no, SwiftUIX is going to be fully backwards compatible with iOS 13. What I meant is, I want start tagging properly post Xcode 12 GM release. This is because I'm currently modifying a bunch of SwiftUIX's APIs (the sign-in with Apple button, for example) to match the iOS 14 APIs to provide backwards compatibility :)

**Comment by joeblau** [comment]
Yes, please tag releases, master is broken right now.

**Comment by vmanot** [comment]
@MatthewCawley @joeblau I've tagged a working master with 0.0.1. It compiles fine for all targets on Xcode 11.6 (the latest GM).

**Comment by vmanot** [comment]
Thank you for your patience folks! Please reopen this issue if you face any troubles with the 0.0.1 tag.

**Comment by joeblau** [comment]
Thanks @vmanot !!

**Comment by vmanot** [comment]
@joeblau SwiftUIX is also going to be a little more proactive [on social media now](https://twitter.com/SwiftUIX), all releases and major project updates will be tweeted there :)

**Comment by MatthewCawley** [comment]
@vmanot Thank you for this by the way :) Sorry it took so long to reply :D
