### ISSUE TITLE
SearchBar onEditingChanged only fired on "searchBarTextDidBeginEditing"

### ISSUE THREAD

**Issue by smaldd14** [SwiftUIX/SwiftUIX#178]
Title says it all... If you change the function 
public func searchBar(_ searchBar: UIViewType, textDidChange searchText: String) {
            base.text = searchText
        }
in SearchBar's Coordinator  to 
public func searchBar(_ searchBar: UIViewType, textDidChange searchText: String) {
            base.text = searchText
            base.onEditingChanged = true
        }

This would fix things I believe.

**Comment by vmanot** [comment]
@smaldd14 this is intentional. If you wish to monitor changes to the text, use one of the extensions on `Binding` offered by SwiftUIX - `$text.onChange({ myText in ... })` to inject a side effect. `onEditingChanged` refers to the "editing" state of the `SearchBar`, just like it works for `TextField` (see relevant discussion [here](https://developer.apple.com/forums/thread/124618?answerId=389554022#389554022)).
