### ISSUE TITLE
Feature Request: allow updating scrollViewConfiguration on CollectionView

### ISSUE THREAD

**Issue by metsfan** [SwiftUIX/SwiftUIX#180]
Hello it seems CollectionView has a property for scrollViewConfiguration but it is not exposed in any way. Would it be possible to make this property mutable? I supposed the same for CocoaList would be useful as well. Thank you!

**Comment by vmanot** [comment]
@metsfan parts of `CocoaScrollViewConfiguration` are already exposed via modifiers such as `onOffsetChange(_:)`, `onRefresh(_:)`, `isRefreshing(_:)` etc. 

If there's a specific property you wish expose, let me know here and I'll add it as a modifier.

**Comment by metsfan** [comment]
Hey I did see those properties, but I'm curious why not expose the entire object? In particular I would like to be able to enable the `pagingEnabled` property for my current use case but I could see the need to modify other properties in the future. It just seems easier from your perspective and mine to expose the ability to provide the entire object.

**Comment by vmanot** [comment]
@metsfan I'm not exposing the whole object because `pagingEnabled` etc. are going to be obsoleted in favor of a larger, more comprehensive rewrite for `CollectionView`. And as for `CocoaScrollView`, I'll be adding preference keys to allow marking entire views as "pages" (allowing for extremely easy and granular paging capabilities) - and if those preferences are exposed paging will automatically be set as true.

I'm closing this issue if it's regarding `pagingEnabled` - but I do intend to write up a discussion in the new Discussions tab regarding the larger rewrite that is coming up. Feel free to reopen if you'd like a specific property to be exposed :)
