### ISSUE TITLE
There has a way to add package by pod?

### ISSUE THREAD

**Issue by Innei** [SwiftUIX/SwiftUIX#213]
I try to add this package by SPM, but cost much time on this process, and hang.

```
Resolving SwiftUIX
String package resolution...
```

![image](https://user-images.githubusercontent.com/41265413/110732056-60f2e580-825e-11eb-9e8f-7ce6b4d0db96.png)

This looks like a bug in Xcode. I try to reset SPM cache, but not working. I try to set a proxy, but it seem to not working, Xcode did't though the proxy.

So, there has a way to add package by pod? I write this in Podfile

```
pod "SwiftUIX"
```

But got a error.

```
Analyzing dependencies
[!] Unable to find a specification for `SwiftUIX`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
# Uncomment the next line to define a global platform for your project
 * not added the source repo that hosts the Podspec to your Podfile.

```

Thank you.

**Comment by vmanot** [comment]
@Innei SwiftUIX currently does not support installation via CocoaPods. As a workaround, I suggest adding SwiftUIX as a git submodule and dragging and dropping it into your Xcode project. I'm closing this issue because CocoaPods is out of scope for the project, but feel free to reopen with any questions related to the suggested workaround!
