### ISSUE TITLE
PaginationView PageControl not showing when alignment is set to .horizontal

### ISSUE THREAD

**Issue by the-braveknight** [SwiftUIX/SwiftUIX#22]
There is an issue inside PaginationView.init where it is always ignoring the passed pageIndicatorAlignment argument (assuming it is always nil is wrong). Also I don't understand this check `if axis == .vertical || pageIndicatorAlignment != .center { ... }` inside PaginationView.body. The PageControl isn't showing when the alignment is horizontal. The check has to be removed and the paddings have to be corrected to account for all pageIndicatorAlignment cases.

**Comment by vmanot** [comment]
@the-braveknight try setting `UIPageControl`'s tint color through `UIAppearance`? Good catch with the parameter being ignored, have fixed it. 

Also, `axis == .vertical || pageIndicatorAlignment != .center` is because I manually create a `UIPageControl` for vertical page view controllers, since Apple doesn't do vertical page controls ¯\_(ツ)_/¯

**Comment by the-braveknight** [comment]
It is partially working now. The indicator is showing if I manually set pageIndicatorAlignment to something other than ".center". Perhaps you should only check for (axis == .vertical) both in PaginationView.body and _PaginationView.makeCoordinator() without (pageIndicatorAlignment != .center).
