### ISSUE TITLE
Documentation Proposal

### ISSUE THREAD

**Issue by matthewrobb** [SwiftUIX/SwiftUIX#315]
First off, thank you so much this package is the only thing making SwiftUI viable in production for large applications.

Members of my team bemoan the lacking documentation. I would love to help get docs up to speed but can't devote a ton of manual time to it in the long term. I am curious if you'd considered and/or have interest in integrating https://github.com/realm/jazzy and generating docs.

The code is fairly well structured and organized, there are few places that are completely lacking in useful comments. I think if you were to adopt this project and output to a gh-pages it would be immensely valuable to the consumers of this package. I would be more than willing to help reformat existing comments and add new where lacking.

Thanks again, let me know what you think!

**Comment by vmanot** [comment]
@matthewrobb Hi Matthew! I share your team's frustration with the lack of documentation, it's a function of bandwidth rather than passion/want (I'm stretched extremely thin between my client work and OSS work). I'm more than happy to accept any new PRs contributing to the documentation, and have been looking into [DocC](https://developer.apple.com/documentation/docc) for rich documentation support. If you're invested in using SwiftUIX and/or would like to discuss further, please free to DM me at `@vatsal_manot` on Twitter :)

**Comment by matthewrobb** [comment]
@vmanot been super swamped the last month or so but plan on circling back on this topic at some point.
