### ISSUE TITLE
How can I remove navigation border ?

### ISSUE THREAD

**Issue by X901** [SwiftUIX/SwiftUIX#352]
Hi ,
Does SwiftUIX have a way to remove navigation border only on one view ? 
I notice when I use code like this 

```
        let coloredAppearance = UINavigationBarAppearance()
        coloredAppearance.configureWithOpaqueBackground()
        coloredAppearance.shadowColor = .clear

        UINavigationBar.appearance().standardAppearance = coloredAppearance
        UINavigationBar.appearance().scrollEdgeAppearance = coloredAppearance

```

it will effect all NavigationViews even if I but it onAppear() 

I want to remove it only on **one view** but show it on all other views

**Comment by vmanot** [comment]
@X901 it does not - and since SwiftUI's `NavigationView` may use a custom navigation bar subclass, I'm going to have to mark this issue out of scope for SwiftUIX unfortunately. You can take a look into the `_configureUINavigationBar` function though, it provides access to the active `UINavigationBar`, if any.
