### ISSUE TITLE
Why 'import Swift'? 

### ISSUE THREAD

**Issue by sammycooks999** [SwiftUIX/SwiftUIX#390]
I noticed in some files you do this: 

```
import Swift 
import SwiftUI

#if os(iOS) || os(tvOS) || targetEnvironment(macCatalyst)
```

and in other files you do this: 

```
#if os(iOS) || os(tvOS) || targetEnvironment(macCatalyst)

import Swift 
import SwiftUI
```

I have a few questions. 

1. Why do you import `Swift`? This isn't needed. 

2. Why do you import `Swift` & `SwiftUI` in one file and then check the operating system with `#if os(iOS) || os(tvOS) || targetEnvironment(macCatalyst)` but then do the exact opposite, checking the operating system before you import `Swift` & `SwiftUI`? 

Thanks for your time.

**Comment by vmanot** [comment]
@sammycooks999 

1. Boring answer, just a personal idiosyncrasy    
2. `Swift` and `SwiftUI` are available on all Apple platforms. `#if os(iOS) || os(tvOS) || targetEnvironment(macCatalyst)` is just a more verbose `#if !os(macOS)` (because simply negating macOS may lead to broken code if Apple introduces a new platform).
