### ISSUE TITLE
Apple defines `scrollDisabled` modifier on the iOS 16

### ISSUE THREAD

**Issue by bryanlee-hdj** [SwiftUIX/SwiftUIX#395]
LIke this title, Apple has released iOS 16 sdk. and it includes the new `scrollDisabled` modifier for the `ScrollView`.

BTW, in the SwiftUIX, there's the same name function in the below path.
 - Sources > Intramodular > Scrolling > EnvironmentValues+ScrollView.swift

What about changing the function name or removing the function?

AFAIK, in the SwiftUIX, the `scrollDisabled` function isn't being used. Instead, the `isScrollEnabled` is being used, even though it has been deprecated(I confirmed it from the message of the function).

**Comment by vmanot** [comment]
@bryanlee-hdj I've updated the code to mark `View.scrollDisabled(_:)` as a disfavored overload, and have also reimplemented it to set SwiftUI's `isScrollEnabled` environment value if running on iOS 16. 

It's useful to otherwise retain the function as-is for two reasons:
- `View.scrollDisabled(_:)` cannot be used in code targeting versions below iOS 16.
-  `scrollDisabled` is the right name for the function.

**Comment by bryanlee-hdj** [comment]
@vmanot Thank you for the fast response & the update!!! 👍
