### ISSUE TITLE
Unable to compile on iOS

### ISSUE THREAD

**Issue by FaizanDurrani** [SwiftUIX/SwiftUIX#87]
Getting this error when trying to compile for iOS.
`Cannot invoke initializer for type '_UIViewControllerLifecycleEventView<Content>.UIViewControllerType' with no arguments`

I believe it's because you're trying to initialise `UIViewControllerType` which extends `UIHostingViewController` so it needs to be initialised with one of the constructors from `UIHostingViewController`.

**Comment by vmanot** [comment]
@FaizanDurrani this is weird - I can't reproduce this on Xcode 11.5 (GM). Could you try updating to the latest commit and check again?

**Comment by BenSova** [comment]
@FaizanDurrani Can you give the path of where the error is occurring? I tried `swift build -v`, but like @vmanot, it's giving me normal results (Except for the ~96 warnings about `Image(systemName:)` on macos). The path to the error shows where the error occurred, whether it is because of SwiftUIX or something in your code (or both).
